# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c130c095d6d9a8d46f86e0effed7176ac13bf2d767c219ab7bfac893b3627e3c5e62dea726ade2c0acb7ddc56962d8a359ab0e465b0e417a337a7d0583db61b

test:
  secret_key_base: fa9c95b2224eb3761e864660fb0f23aa97c1e4d527ed1406c6939b48dd723441ebe81c2683b2bcd178161390477b502673f198741f76ac9b97d7a93db3b7aab6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
